# Generated by Django 3.2.7 on 2021-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mask_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('mask_detection', models.BooleanField()),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('table_id', models.IntegerField()),
                ('person_count', models.IntegerField()),
                ('alarm_detection', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wash_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('wash_detection', models.IntegerField()),
            ],
        ),
    ]
