# Generated by Django 3.2.7 on 2021-10-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wash_history',
            name='wash_detection',
        ),
        migrations.AddField(
            model_name='wash_history',
            name='step_1',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='wash_history',
            name='step_2',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='wash_history',
            name='step_3',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='wash_history',
            name='step_4',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='table_history',
            name='event_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
