# Generated by Django 3.2.7 on 2021-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acto', '0002_auto_20211029_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_history',
            name='img_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
